<a href="https://colab.research.google.com/github/btaitel/flaming-octo-nemesis/blob/master/Module%201/Session%201/s16nb2_pandas_functions_SP25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Functions: Index, Concat, Merge

***
## The content of this notebook is a continuation of the Pandas classroom lectures conducted by Professor Vuduc. These lectures are posted as videos on Canvas, under Topic 7.

## This notebook presupposes that students have already watched those videos, and that they have some understanding of the content.

## We will not be covering, or answering questions about, that foundational content here.

## Please post any questions about that content to Piazza.
***

**The below three cells simply set up the NB with the same two df's as in Professor Vuduc's classroom lectures.**

In [1]:
import pandas as pd  # Standard idiom for loading pandas
from pandas import DataFrame, Series
import numpy as np

In [2]:
cafes = DataFrame({'name': ['east pole', 'chrome yellow', 'brash', 'taproom', '3heart', 'spiller park pcm', 'refuge', 'toptime'],
                   'zip': [30324, 30312, 30318, 30317, 30306, 30308, 30303, 30318],
                   'poc': ['jared', 'kelly', 'matt', 'jonathan', 'nhan', 'dale', 'kitti', 'nolan']})

cafes2 = cafes[['poc', 'zip']] #didnt use .loc
cafes2.index = cafes['name']
cafes2.index.name = None

In [9]:
cafes2

                       poc    zip  rating price  value
east pole            jared  30324     4.0    $$    2.0
chrome yellow        kelly  30312     4.0    $$    2.0
brash                 matt  30318     4.0    $$    2.0
taproom           jonathan  30317     4.0    $$    2.0
3heart                nhan  30306     4.0    $$    2.0
spiller park pcm      dale  30308     4.0    $$    2.0
refuge               kitti  30303     4.0    $$    2.0
toptime              nolan  30318     4.0    $$    2.0

In [12]:
cafes3

                       poc    zip  rating price  value
east pole            jared  30324     4.0    $$    2.0
chrome yellow        kelly  30312     4.0    $$    2.0
brash                 matt  30318     4.0    $$    2.0
taproom           jonathan  30317     4.0    $$    2.0
3heart                nhan  30306     4.0    $$    2.0
spiller park pcm      dale  30308     4.0    $$    2.0
refuge               kitti  30303     4.0    $$    2.0
toptime              nolan  30318     4.0    $$    2.0

In [13]:
cafes2['rating'] = 4.0 #every cafe will have this rating
cafes2['price'] = '$$' #every cafe will have this price
prices_as_ints = cafes2['price'].apply(lambda s: len(s)) #using price column and to createa new col (series)
cafes2['value'] = cafes2['rating'] / prices_as_ints #rating divided by len of price
cafes3 = cafes2.copy()
is_fancy = cafes3['zip'].isin({30306, 30308})
cafes3.loc[is_fancy, 'price'] += '$' #he says its like a conditional, to know where to add the extra $
cafes4 = cafes3.copy()
def calc_value(row):
    return row['rating'] / len(row['price'])

cafes4['value'] = cafes4.apply(calc_value, axis=1)
cafes4

                       poc    zip  rating price     value
east pole            jared  30324     4.0    $$  2.000000
chrome yellow        kelly  30312     4.0    $$  2.000000
brash                 matt  30318     4.0    $$  2.000000
taproom           jonathan  30317     4.0    $$  2.000000
3heart                nhan  30306     4.0   $$$  1.333333
spiller park pcm      dale  30308     4.0   $$$  1.333333
refuge               kitti  30303     4.0    $$  2.000000
toptime              nolan  30318     4.0    $$  2.000000

In [8]:
type(prices_as_ints)

pandas.core.series.Series

## Index objects

A pandas [`Index`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Index.html), used by `Series` and `DataFrame`, is "list-like." It has a number of useful operations, including set-like operations (e.g., testing for membership, intersection, union, difference).

https://pandas.pydata.org/pandas-docs/stable/reference/indexing.html

In [14]:
from pandas import Index

In [15]:
# what are the index names?
cafes4.index

Index(['east pole', 'chrome yellow', 'brash', 'taproom', '3heart',
       'spiller park pcm', 'refuge', 'toptime'],
      dtype='object')

#### Index values can be duplicated, so there can be more than one row with the same index value.

In [16]:
idx = pd.Index(['Labrador', 'Beagle', 'Labrador',
                      'Lhasa', 'Husky', 'Beagle'])

# Print the Index
idx

Index(['Labrador', 'Beagle', 'Labrador', 'Lhasa', 'Husky', 'Beagle'], dtype='object')

We can use the `Index.duplicated()` function to identify all the duplicate values.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.duplicated.html

In the example below, all the duplicate values will be marked as `True`.

In [18]:
# Identify all duplicated occurrence of values
idx.duplicated(keep = False)

array([ True,  True,  True, False, False,  True])

The `isin()` function returns a boolean mask array, in which each row of the mask array has a `True/False` value, if that row meets or does not meet the `isin()` criteria.

We will cover boolean masks in some detail in tomorrow's session.

In [21]:
# boolean mask/membership
display(cafes4.index)
cafes4.index.isin(['brash', '3heart'])

Index(['east pole', 'chrome yellow', 'brash', 'taproom', '3heart',
       'spiller park pcm', 'refuge', 'toptime'],
      dtype='object')

array([False, False,  True, False,  True, False, False, False])

#### The next few cells show index operations, to illustrate some things that you can do with indexes.

In [24]:
# create an union with a new value
cafes4.index.union(['chattahoochee','brash'])

#union = combine those lists together into one, but no doops
# ^ like how brash is only once even though its in both lists

Index(['3heart', 'brash', 'chattahoochee', 'chrome yellow', 'east pole',
       'refuge', 'spiller park pcm', 'taproom', 'toptime'],
      dtype='object')

In [26]:
# return the difference
cafes4.index.difference(['chattahoochee', 'starbucks', 'bar crema','brash'])

Index(['3heart', 'chrome yellow', 'east pole', 'refuge', 'spiller park pcm',
       'taproom', 'toptime'],
      dtype='object')

If you need to change the index of a `DataFrame`, here is one way to do it.

In [27]:
cafes5 = cafes4.reindex(Index(['3heart', 'east pole', 'brash', 'starbucks']))

#reindex could be used for reordering
display(cafes4)
display(cafes5)

                       poc    zip  rating price     value
east pole            jared  30324     4.0    $$  2.000000
chrome yellow        kelly  30312     4.0    $$  2.000000
brash                 matt  30318     4.0    $$  2.000000
taproom           jonathan  30317     4.0    $$  2.000000
3heart                nhan  30306     4.0   $$$  1.333333
spiller park pcm      dale  30308     4.0   $$$  1.333333
refuge               kitti  30303     4.0    $$  2.000000
toptime              nolan  30318     4.0    $$  2.000000

             poc      zip  rating price     value
3heart      nhan  30306.0     4.0   $$$  1.333333
east pole  jared  30324.0     4.0    $$  2.000000
brash       matt  30318.0     4.0    $$  2.000000
starbucks    NaN      NaN     NaN   NaN       NaN

Observe that this reindexing operation matches the supplied index values against the existing ones. (What happens to index values you leave out? What happens with new index values?)

### Tap, tap, tap

**Below is an index operation that is useful. You will see this in future NB's and can expect to be asked to apply this funcationality in testing scenarios (MT2 and Final exam).**

**As an aside, you can expect to be required to show your proficiency with everything in this NB on the exams.**

Another useful operation is dropping the index (and replacing it with the default, integers).

In [28]:
# display for initial reference
cafes4

                       poc    zip  rating price     value
east pole            jared  30324     4.0    $$  2.000000
chrome yellow        kelly  30312     4.0    $$  2.000000
brash                 matt  30318     4.0    $$  2.000000
taproom           jonathan  30317     4.0    $$  2.000000
3heart                nhan  30306     4.0   $$$  1.333333
spiller park pcm      dale  30308     4.0   $$$  1.333333
refuge               kitti  30303     4.0    $$  2.000000
toptime              nolan  30318     4.0    $$  2.000000

In [29]:
# create a new df, cafes6, and
# reset the index from the string names to integers
cafes6 = cafes4.reset_index(drop=True)
cafes6

        poc    zip  rating price     value
0     jared  30324     4.0    $$  2.000000
1     kelly  30312     4.0    $$  2.000000
2      matt  30318     4.0    $$  2.000000
3  jonathan  30317     4.0    $$  2.000000
4      nhan  30306     4.0   $$$  1.333333
5      dale  30308     4.0   $$$  1.333333
6     kitti  30303     4.0    $$  2.000000
7     nolan  30318     4.0    $$  2.000000

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html

From the documentation:  Reset the index of the DataFrame, and use the default one instead.

In [30]:
# create a new column from the index of the other df
# recall that the other index is strings
cafes6['name'] = cafes4.index
cafes6

        poc    zip  rating price     value              name
0     jared  30324     4.0    $$  2.000000         east pole
1     kelly  30312     4.0    $$  2.000000     chrome yellow
2      matt  30318     4.0    $$  2.000000             brash
3  jonathan  30317     4.0    $$  2.000000           taproom
4      nhan  30306     4.0   $$$  1.333333            3heart
5      dale  30308     4.0   $$$  1.333333  spiller park pcm
6     kitti  30303     4.0    $$  2.000000            refuge
7     nolan  30318     4.0    $$  2.000000           toptime

### Now let's look at the concat() function.

Another useful operation is gluing `DataFrame` objects together. There are several helpful operations covered in Notebook 7; one not mentioned there, but useful in one of its exercises, is `.concat()`.

The below material is partially adapted from "The Python Data Science Handbook" by Jake VanderPlas, Chapter 3.

Here is the documentation page for .concat():

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

Note that the only arguments required are the objects to be concatenated.

1. The default axis=0, which means the concatenation is done along the indexes (rows). From a practical perspective, what this means is that the second listed df (or 3rd, 4th, etc) is "attached" to the bottom of the 1st listed dataframe.

2. The default join is 'outer' join, which means to bring all rows in. We will cover joins in detail during our SQL module, but in this case, the outer join means to bring in all rows from both dataframes.

3. Pandas concatenation preserves indexes, even if the result will have duplicate indexes. The verify_integrity option handles duplicates, and please see the documentation for specifics. You will generally not need to worry about this option during the class.

So let's look at an example.

In [32]:
cafes4

                       poc    zip  rating price     value
east pole            jared  30324     4.0    $$  2.000000
chrome yellow        kelly  30312     4.0    $$  2.000000
brash                 matt  30318     4.0    $$  2.000000
taproom           jonathan  30317     4.0    $$  2.000000
3heart                nhan  30306     4.0   $$$  1.333333
spiller park pcm      dale  30308     4.0   $$$  1.333333
refuge               kitti  30303     4.0    $$  2.000000
toptime              nolan  30318     4.0    $$  2.000000

In [33]:
# Split based on price

# create a boolean mask aka a series with the index and price col and  trues and falses
is_cheap = cafes4['price'] <= '$$' #they are using comparison operator on string, we know it will be only money signs

# create 2 df's, based on the mask
cafes_cheap = cafes4[is_cheap]   #cheap
cafes_pricey = cafes4[~is_cheap]  #not cheap, looks like squiggly line is NOT

display(cafes_cheap)
display(cafes_pricey)

                    poc    zip  rating price  value
east pole         jared  30324     4.0    $$    2.0
chrome yellow     kelly  30312     4.0    $$    2.0
brash              matt  30318     4.0    $$    2.0
taproom        jonathan  30317     4.0    $$    2.0
refuge            kitti  30303     4.0    $$    2.0
toptime           nolan  30318     4.0    $$    2.0

                   poc    zip  rating price     value
3heart            nhan  30306     4.0   $$$  1.333333
spiller park pcm  dale  30308     4.0   $$$  1.333333

In [34]:
# Never mind; recombine
pd.concat([cafes_cheap, cafes_pricey])

                       poc    zip  rating price     value
east pole            jared  30324     4.0    $$  2.000000
chrome yellow        kelly  30312     4.0    $$  2.000000
brash                 matt  30318     4.0    $$  2.000000
taproom           jonathan  30317     4.0    $$  2.000000
refuge               kitti  30303     4.0    $$  2.000000
toptime              nolan  30318     4.0    $$  2.000000
3heart                nhan  30306     4.0   $$$  1.333333
spiller park pcm      dale  30308     4.0   $$$  1.333333

The .concate() function will bring together dataframes with the same column names and will also join those with different column names. In general, we will not exercise the latter case in this class, but there are numerous examples available online which show how pandas does this. A very good reference with examples is VanderPlas:

https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html

https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.06-Concat-And-Append.ipynb

### Next is the merge() function.

One essential feature offered by Pandas is its high-performance, in-memory join and merge operations.
If you have ever worked with databases, you should be familiar with this type of data interaction.

In SQL, this is a select and join of two tables.

The main interface for this is the ``pd.merge`` function, which you will use extensively in this class.

Here is the documentation page for .merge():

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html

The first 6 parameters are important for us to know about, and to know how to use. You may use the remaining parameters, but these first 6 are absolutely necessary for you to understand and use.

**pandas.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)**


1. The 'left' and 'right' parameters define the two dataframes to merge on. It is important for you to designate and remember which df is left and which is right, as 3 of the 4 remaining parameters use them.

2. The 'how' parameter designates the type of join operation to perform (left, right, outer, inner, cross). We will cover these in detail during our SQL module next week.

3. The 'on' parameter gives the column(s) or index level names to join on. Whatever you designate for this parameter must be contained in both the left and right df's.

4. You can use the 'left_on' and 'right_on' parameters when the two dataframes do not have identically-named columns, but they have differently-named columns that have the same values, and you can join on them. We will show an example of this below.

**Specifying the merge key:**

The default behavior of pd.merge() is that it looks for one or more matching column names between the two inputs, and uses this as the key. Note that the default value for the 'on' parameter is None, so if you do not specify the column names to merge on, the function will attempt to execute its default behavior.

However, often the column names will not match so nicely, and pd.merge() provides a variety of options for handling this.

You have several options for specifying how to merge:

1. You can explicitly specify the name of the key column using the on keyword, which takes a column name or a list of column names. Note that this only works if both the left and right dataframes have the specified column name.

2. The left_on and right_on keywords are useful when you want to merge two datasets with different column names.

In [35]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue','Chris','Rich'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR','IT','Engineering']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display(df1, df2,df3)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4    Chris           IT
5     Rich  Engineering

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [36]:
# option 1 above, using on
display(df1, df2, pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4    Chris           IT
5     Rich  Engineering

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [37]:
# option 2 above, using left_on and right_on
# note the designation of the left and right df's, and then using the correct *_on column names
display(df1, df3, pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4    Chris           IT
5     Rich  Engineering

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

**The default value for the 'how' parameter is inner. As the documentation states:  inner: use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys.**

In layman's terms, what this means is that the only keys returned will be those that are in both the left and right df's.

Review againg the first join between df1 and df2. The key values from df2 of 'Rich' and 'Chris' are not in df1, so they are not included in the inner join.

So let's set the join to outer and see what happens.**Again, from the documentation:  outer: use union of keys from both frames, similar to a SQL full outer join; sort keys lexicographically.**

Additionally, the outer join fills in all missing values with NAs.

In [38]:
# option 1 above, using on, this time as an outer join
display(df1, df2, pd.merge(df1, df2, on='employee', how='outer'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4    Chris           IT
5     Rich  Engineering

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting     2008.0
1    Chris           IT        NaN
2     Jake  Engineering     2012.0
3     Lisa  Engineering     2004.0
4     Rich  Engineering        NaN
5      Sue           HR     2014.0

See the 'hire_date' values for Chris and Rich, they are NaN values, as specified.

We will spend more time on the join types in SQL next week, and know that all of the behaviors you will learn about then will apply here. We simply want to introduce you to the function here.

As noted above, the VanderPlas book has excellent coverage of this topic:

https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html

https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.07-Merge-and-Join.ipynb

**This concludes our introduction to some important pandas functions.**

**We encourage you to delve deeper into them, as you will be using all of these throughout this class and professionally in working with Python for Analytics.**

**We also highly encourage you to work through NB7 Part1, the FEC Dataset notebook, as is does a full analysis of 'real life' data from the Federal Election Commission, including application of the above functions that we have covered here.**